nodeLinker: node-modules

<<<<<<< HEAD
=======
plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

>>>>>>> 13d8c47441ba3f1c668b617fc02dd2fad8ad9f5b
yarnPath: .yarn/releases/yarn-3.2.2.cjs
